version: '3.8'

services:
  chatgram:
    restart: always
    build:
      context: ./
    depends_on:
      - pg

  pg:
    restart: always
    image: postgres:latest
    volumes:
      - ././database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
