version: '3.8'

services:
  nestjs:
    restart: always
    build:
      context: ./
    depends_on:
      - pg
    environment:
      - POSTGRES_HOST=pg
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=postgres
    ports:
      - 8080:8080

  pg:
    restart: always
    image: postgres:latest
    volumes:
      - ././database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
